import { Bonplan } from "./bonplan";

export const BONPLAN: Bonplan[] = [
    {
        ville_name:"Grenoble",
        activity_type:"Course",
        name:"Oussa",
        address:"Monte la Bastille"
    },
    {
        ville_name:"Grenoble",
        activity_type:"Course",
        name:"Oussabien",
        address:"Descend de la Bastille"
    },
    {
        ville_name:"Grenoble",
        activity_type:"Ski",
        name:"Quisa",
        address:"Vercors"
    },
    {
        ville_name:"Grenoble",
        activity_type:"Ski",
        name:"Chaussettes",
        address:"Beldone"
    },
    {
        ville_name:"Grenoble",
        activity_type:"Randonne",
        name:"Chaussures",
        address:"Trounoir"
    },
    {
        ville_name:"Grenoble",
        activity_type:"Randonne",
        name:"Tropnul",
        address:"Troublanc"
    },
    {
        ville_name:"Lyon",
        activity_type:"Course",
        name:"Fort",
        address:"Tetedor"
    },{
        ville_name:"Lyon",
        activity_type:"Course",
        name:"Faible",
        address:"Meribellejaunage"
    },{
        ville_name:"Lyon",
        activity_type:"Course",
        name:"Moyen",
        address:"PartDieu"
    },{
        ville_name:"Lyon",
        activity_type:"Piscine",
        name:"Moulebite",
        address:"BordureRhone"
    },{
        ville_name:"Lyon",
        activity_type:"Piscine",
        name:"Short",
        address:"Eaudouce"
    },{
        ville_name:"Marseille",
        activity_type:"Course",
        name:"Plage",
        address:"Sable"
    },{
        ville_name:"Marseille",
        activity_type:"Course",
        name:"Route",
        address:"Cailloux"
    },

]